[workspace]
members = ["web", "qr", "qr-macro", "js-macro", "leptos_static_files", "oembed", "oembed-macro", "oembed-type", "wasm-data-merger"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0"
any_spawner = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug" }
axum = { version = "0.8.1", default-features = false }
base64 = "0.22.1"
chrono = { version = "0.4.44", default-features = false, features = ["std", "alloc"] }
cargo-leptos = "0.3.7"
conditionraise.path = "./web"
console_error_panic_hook = "0.1.7"
futures = { version = "0.3", default-features = false }
hydration_context = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug" }
image = { version = "0.25", default-features = false, features = ["png"] }
js-macro.path = "./js-macro"
leptos = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug", default-features = false }
leptos_axum = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug" }
leptos_integration_utils = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug" }
leptos_meta = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug", default-features = false }
leptos_static_files.path = "./leptos_static_files"
 leptos_router = { git = "https://github.com/Ofenhed/leptos", branch = "nonce-bug", default-features = false }
libc = "0.2"
oembed.path = "./oembed"
oembed-macro.path = "./oembed-macro"
oembed-type.path = "./oembed-type"
proc-macro2 = "1.0.106"
qr.path = "./qr"
qr-macro.path = "./qr-macro"
qrcode = { version = "0.14.1", default-features = false }
quote = "1.0.45"
reactive_graph = "0.2"
reqwest = "0.13"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10"
strum = "0.28"
swc = { version = "55", default-features = false }
swc_common = { version = "18", default-features = false }
syn = { version = "3", default-features = false }
thiserror = "2.0.12"
tokio = { version = "1.39", default-features = false }
tokio-util = { version = "0.7", default-features = false }
url = { version = "2.5", default-features = false }
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.98", default-features = false }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
