name: Publish to github.io

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  cargo_leptos_version: ./target/.cargo-leptos-version

jobs:
  move-last-artifact:
    runs-on: ubuntu-latest
    outputs:
      old-wasm: ${{ steps.upload-wasm-file.outputs.artifact-id }}

    steps:
    - name: Download artifact from latest build
      uses: dawidd6/action-download-artifact@v21
      id: get-old-wasm
      continue-on-error: true
      with:
        name: wasm-file
        workflow_conclusion: success
        branch: master

    - name: Save wasm as previous
      uses: actions/upload-artifact@v7
      if: steps.get-old-wasm.outcome == 'success'
      id: upload-wasm-file
      with:
        name: old-wasm-file
        path: conditionraise.wasm

  build:
    if: ${{ always() }}

    runs-on: ubuntu-latest
    needs: move-last-artifact

    outputs:
      wasm: ${{ steps.upload-wasm-file.outputs.artifact-id }}

    steps:
    - uses: actions/checkout@v6

    - name: Restore cache
      id: cache-primes-restore
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-leptos-
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos
          target/release
          target/front

    - name: Use nightly rust
      run: rustup override set nightly

    - name: Log rust version
      run: rustup --version

    - name: Check if leptos toolkit was cached
      id: cargo-leptos-cached
      run: test -f ~/.cargo/bin/cargo-leptos
      continue-on-error: true

    - name: Build leptos toolkit
      id: cargo-leptos-build
      if: steps.cargo-leptos-cached.outcome == 'failure'
      run: cargo install cargo-leptos --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Check cargo-leptos version
      id: write-cargo-leptos-version
      run: cargo info cargo-leptos | tee "$cargo_leptos_version"

    - name: Check saved leptos version
      id: check-cache-cargo-leptos-version
      if: steps.write-cargo-leptos-version.outcome == 'success'
      continue-on-error: true
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-leptos-${{ hashFiles(env.cargo_leptos_version) }}
        lookup-only: true
        fail-on-cache-miss: true
        path: |
          ~/.cargo/bin/cargo-leptos

    - name: Save leptos cache
      if: steps.check-cache-cargo-leptos-version.outcome == 'failure'
      uses: actions/cache/save@v5
      with:
        key: ${{ runner.os }}-leptos-${{ hashFiles(env.cargo_leptos_version) }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos

    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: Compile targets
      run: cargo leptos build --release --bin-features ssr,statics

    - name: Save full cache
      uses: actions/cache/save@v5
      if: always()
      with:
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos
          target/release
          target/front

    - name: Generate static files
      run: target/release/conditionraise

    - name: Upload site root
      uses: actions/upload-pages-artifact@v5
      id: deployment
      with:
        path: target/site/

    - name: Save wasm file
      uses: actions/upload-artifact@v7
      id: upload-wasm-file
      with:
        name: wasm-file
        path: target/site/pkg/conditionraise.wasm

  check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build
      - move-last-artifact

    steps:
    - uses: actions/checkout@v6

    - name: Restore tool cache
      id: cache-tools-restore
      continue-on-error: true
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-check-tools-${{ hashFiles('**/Cargo.lock') }}
        fail-on-cache-miss: true
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/leptosfmt
          ~/.cargo/bin/twiggy

    - name: Use nightly rust
      run: rustup override set nightly && rustup component add rustfmt

    - name: Log rust version
      run: rustup --version

    - name: Rust formatting
      run: cargo fmt --check --all

    - name: Check if leptosfmt was cached
      id: leptosfmt-cached
      run: test -f ~/.cargo/bin/leptosfmt
      continue-on-error: true

    - name: Check if twiggy was cached
      id: twiggy-cached
      run: test -f ~/.cargo/bin/twiggy
      continue-on-error: true

    - name: Install leptosfmt
      if: steps.leptosfmt-cached.outcome == 'failure'
      run: cargo install leptosfmt --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Install twiggy
      if: steps.twiggy-cached.outcome == 'failure'
      run: cargo install twiggy --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Save tool cache
      uses: actions/cache/save@v5
      if: steps.cache-tools-restore.outcome == 'failure'
      with:
        key: ${{ steps.cache-tools-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/leptosfmt
          ~/.cargo/bin/twiggy

    - name: Leptos view formatting
      run: leptosfmt --check web/

    - name: Download wasm binary
      uses: actions/download-artifact@v8
      id: get-wasm
      with:
        artifact-ids: ${{ needs.build.outputs.wasm }}
        path: target/site/pkg/

    - name: Check target binary bloat
      run: |
        twiggy top target/site/pkg/conditionraise.wasm
        twiggy monos target/site/pkg/conditionraise.wasm
        twiggy garbage target/site/pkg/conditionraise.wasm

    - name: Download previous wasm binary
      uses: actions/download-artifact@v8
      id: get-old-wasm
      with:
        artifact-ids: ${{ needs.move-last-artifact.outputs.wasm }}
        path: target/site.old/pkg/

    - name: Check target binary bloat
      if: steps.get-old-wasm.outcome == 'success'
      run: twiggy diff target/site.old/pkg/conditionraise.wasm  target/site/pkg/conditionraise.wasm


  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
    - name: Deploy artifact
      uses: actions/deploy-pages@v5
      id: deployment
