name: Publish to github.io

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Restore cache
      id: cache-primes-restore
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-leptos-
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos
          target/release
          target/front

    - name: Use nightly rust
      run: rustup override set nightly

    - name: Log rust version
      run: rustup --version

    - name: Check if leptos toolkit was cached
      id: cargo-leptos-cached
      run: test -f ~/.cargo/bin/cargo-leptos
      continue-on-error: true

    - name: Build leptos toolkit
      id: cargo-leptos-build
      if: steps.cargo-leptos-cached.outcome == 'failure'
      run: cargo install cargo-leptos --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Read toolkit info
      id: read-cargo-leptos-info
      run: mkdir -p ./target && (cargo info cargo-leptos | tee ./target/.cargo-leptos-version)

    - name: Check saved leptos version
      id: check-cache-cargo-leptos-version
      if: steps.read-cargo-leptos-info.outcome == 'success'
      continue-on-error: true
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-leptos-${{ hashFiles('./target/.cargo-leptos-version') }}
        lookup-only: true
        path: |
          ~/.cargo/bin/cargo-leptos

    - name: Save leptos cache
      if: steps.check-cache-cargo-leptos-version.outcome != 'failure'
      uses: actions/cache/save@v5
      with:
        key: ${{ runner.os }}-leptos-${{ hashFiles('./target/.cargo-leptos-version') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos

    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: Compile targets
      run: cargo leptos build --release --bin-features ssr,statics

    - name: Save full cache
      uses: actions/cache/save@v5
      if: always()
      with:
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos
          target/release
          target/front

    - name: Generate static files
      run: target/release/conditionraise

    - name: Upload site root
      uses: actions/upload-pages-artifact@v5
      id: deployment
      with:
        path: target/site/

  check:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v6

    - name: Restore build cache
      id: cache-primes-restore
      uses: actions/cache/restore@v5
      with:
        key: ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.lock') }}
        fail-on-cache-miss: true
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/cargo-leptos
          target/release
          target/front

    - name: Use nightly rust
      run: rustup override set nightly && rustup component add rustfmt

    - name: Log rust version
      run: rustup --version

    - name: Rust formatting
      run: cargo fmt --check --all

    - name: Install leptosfmt
      run: cargo install leptosfmt --locked

    - name: Leptos view formatting
      run: leptosfmt --check web/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
    - name: Deploy artifact
      uses: actions/deploy-pages@v5
      id: deployment
