name: Publish to github.io

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  cargo_leptos_version: ./.cargo-leptos-version
  rust_version: ./.rust-version
  LEPTOS_SITE_PKG_DIR: pkg-${{ github.run_number }}

jobs:
  build:
    name: Build static files

    runs-on: ubuntu-latest

    outputs:
      wasm: ${{ steps.upload-wasm-file.outputs.artifact-id }}

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ case(github.event_name == 'workflow_dispatch', inputs.ref, github.ref) }}

    - name: Check locked cargo-leptos version
      id: write-cargo-leptos-version
      run: |
        awk '/\[\[package\]\]/ { right_place=0; checksum = null }; /name\s*=\s*"cargo-leptos"/ { right_place=1; }; /checksum\s*=/ { checksum=$0 }; { if (right_place && checksum != null) { print(checksum); exit }  }' < Cargo.lock | tee "$cargo_leptos_version"

    - name: Use nightly rust
      run: rustup override set nightly

    - name: Log rust version
      run: rustc --version | tee "$rust_version"

    - name: Restore build cache
      id: cache-primes-restore
      uses: actions/cache/restore@v6
      with:
        key: ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock', env.rust_version) }}
        restore-keys: |
          ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.toml') }}-
          ${{ runner.os }}-cargo-lock-
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/front
          target/oembed
          target/qr
          target/release

    - name: Restore cargo-leptos
      id: cargo-leptos-restore
      if: ${{ !cancelled() }}
      uses: actions/cache/restore@v6
      with:
        key: ${{ runner.os }}-cargo-leptos-${{ hashFiles(env.cargo_leptos_version) }}
        path: |
          ~/.cargo/bin/cargo-leptos

    - name: Build leptos toolkit
      id: cargo-leptos-build
      if: ${{ !steps.cargo-leptos-restore.outputs.cache-hit && !cancelled() }}
      run: cargo install cargo-leptos --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Save leptos cache
      if: ${{ steps.cargo-leptos-build.outcome == 'success' && !cancelled() }}
      uses: actions/cache/save@v6
      with:
        key: ${{ steps.cargo-leptos-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/bin/cargo-leptos

    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: Compile file generator
      id: compile
      if: ${{ !cancelled() && hashFiles("target/qr/qrcode.png") == '' }}
      run: cargo leptos build --split --server-only --release --bin-features ssr,statics

    - name: Generate initial files
      if: ${{ !cancelled() && step.compile.outcome == 'success' }}
      run: target/release/conditionraise

    - name: Recompile targets
      id: recompile
      run: cargo leptos build --split --release --bin-features ssr,statics,static-qr

    - name: Save build cache
      uses: actions/cache/save@v6
      if: ${{ steps.recompile.outcome == 'success' || steps.recompile.outcome == 'failure' }}
      with:
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/front
          target/oembed
          target/qr
          target/release

    - name: Regenerate static files
      run: target/release/conditionraise

    - name: Upload site root
      uses: actions/upload-pages-artifact@v5
      id: deployment
      with:
        path: target/site/

    - name: Save wasm file
      uses: actions/upload-artifact@v7
      id: upload-wasm-file
      with:
        name: wasm-file
        path: target/front/wasm32-unknown-unknown/wasm-release/conditionraise.wasm

    - name: Log compiled sizes
      run: find target/site/ -exec du -sh {} \;

  check:
    name: Check source code rules
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v6

    - name: Restore tool cache
      id: cache-tools-restore
      continue-on-error: true
      uses: actions/cache/restore@v6
      with:
        key: ${{ runner.os }}-check-tools-${{ hashFiles('**/Cargo.lock') }}
        fail-on-cache-miss: true
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/leptosfmt
          ~/.cargo/bin/twiggy

    - name: Use nightly rust
      run: rustup override set nightly && rustup component add rustfmt clippy

    - name: Log rust version
      run: rustc --version | tee "$rust_version"

    - name: Restore build cache
      id: cache-primes-restore
      uses: actions/cache/restore@v6
      with:
        key: ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock', env.rust_version) }}
        restore-keys: |
          ${{ runner.os }}-cargo-lock-${{ hashFiles('**/Cargo.toml') }}-
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/front
          target/oembed
          target/qr
          target/release

    - name: Check if leptosfmt was cached
      id: leptosfmt-cached
      continue-on-error: true
      run: test -f ~/.cargo/bin/leptosfmt

    - name: Check if twiggy was cached
      id: twiggy-cached
      continue-on-error: true
      run: test -f ~/.cargo/bin/twiggy

    - name: Install leptosfmt
      if: ${{ steps.leptosfmt-cached.outcome == 'failure' && !cancelled() }}
      run: cargo install leptosfmt --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Install twiggy
      if: ${{ steps.twiggy-cached.outcome == 'failure' && !cancelled() }}
      run: cargo install twiggy --locked
      env:
        CARGO_TARGET_DIR: ./target

    - name: Save tool cache
      uses: actions/cache/save@v6
      if: ${{ steps.cache-tools-restore.outcome == 'failure' && !cancelled() }}
      with:
        key: ${{ steps.cache-tools-restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin/leptosfmt
          ~/.cargo/bin/twiggy

    - name: Setup completed
      id: setup-completed
      run: mkdir -p target/qr && touch target/qr/qrcode.png

    - name: Clippy analysis
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}
      run: cargo clippy --no-deps --release --all-features -- -Dwarnings

    - name: Rust formatting
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}
      run: cargo fmt --check --all

    - name: Leptos view formatting
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}
      run: leptosfmt --check web/

    - name: Download wasm binary
      uses: actions/download-artifact@v8
      id: get-wasm
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}
      with:
        artifact-ids: ${{ needs.build.outputs.wasm }}
        path: target/new

    - name: Check twiggy top
      run: twiggy top target/new/conditionraise.wasm
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}

    - name: Check twiggy monos
      run: twiggy monos target/new/conditionraise.wasm
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}

    - name: Check twiggy garbage
      run: twiggy garbage --all target/new/conditionraise.wasm
      if: ${{ steps.setup-completed.outcome == 'success' && !cancelled() }}

    - name: Download artifact from latest build
      uses: dawidd6/action-download-artifact@v21
      id: get-old-wasm
      if: ${{ steps.get-wasm.outcome == 'success' && !cancelled() }}
      continue-on-error: true
      with:
        name: wasm-file
        path: target/old
        workflow_conclusion: success
        branch: master

    - name: Check target size change
      if: ${{ steps.get-old-wasm.outcome == 'success' && !cancelled() }}
      run: twiggy diff target/old/conditionraise.wasm  target/new/conditionraise.wasm

  deploy:
    name: Deploy to Github Pages
    if: ${{ !cancelled() && (github.event_name == 'workflow_dispatch' || github.event_name == 'push') }}
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}

    steps:
    - name: Deploy artifact
      uses: actions/deploy-pages@v5
      id: deployment
